#READ ME
##CPSC 483 project 6
Adam Shirley  
bsa919adam@csu.fullerton.edu
###Project Summary 
This project requires the creation of a KNN, Naive Bayes, and SVM for bank data collected by UCI, the goal is to predict whether they said yes or not. The point is to semonstrate that sometimes due to there being to many of one class versus the other it is nessecary to resample the data to minimize the effect of this


In [140]:
import numpy as np
import pandas as pd
from sklearn import naive_bayes, neighbors, svm, metrics
from imblearn.over_sampling import RandomOverSampler


### Experiment 2

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [108]:

training_set = pd.read_csv("/content/drive/MyDrive/bank-additional/bank-additional.csv", delimiter = ';')
test_set = pd.read_csv("/content/drive/MyDrive/bank-additional/bank-additional-full.csv", delimiter = ';')

### Experiment 3a

In [109]:
test_set = test_set.dropna()

training_set = pd.get_dummies(training_set, drop_first= True)
test_set = pd.get_dummies(test_set, drop_first= True)


### Experiment 3b

In [110]:
if 'duration' in training_set.columns:
    training_set.pop('duration')
if 'duration' in test_set.columns:
    test_set.pop('duration')

In [111]:

if 'y_yes' in training_set.columns:
    training_target = training_set.pop('y_yes')
if 'y_yes' in test_set.columns:
    test_target = test_set.pop('y_yes')

In [112]:
test_target.shape

(41188,)

In [113]:
test_set.shape

(41188, 52)

### Experiment 3c

In [114]:
to_normalize = ['age', 'campaign', 'pdays', 'previous', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed']

for label in to_normalize:
    mean =  training_set[label].mean()
    std = training_set[label].std()
    print(std)
    training_set[label] = (training_set[label] - mean)/std
    test_set[label] = (test_set[label] - mean)/std


10.313361547199822
2.5681592375781075
191.9227858007736
0.5417883234290218
1.5631144559116605
0.5793488049889658
4.594577506837506
1.7335912227013601
73.66790355721277


### Experiment 4

In [142]:
gnb = naive_bayes.GaussianNB().fit(training_set, training_target)
gnb_training_score = gnb.score(training_set, training_target)
gnb_test_score = gnb.score(test_set, test_target)
print('Naive Bayes training score = ', gnb_training_score)
print("Naive Bayes test score = ", gnb_test_score)

Naive Bayes training score =  0.5906773488710853
Naive Bayes test score =  0.5993736039623191


In [118]:
knn = neighbors.KNeighborsClassifier().fit(training_set, training_target)
knn_training_score = knn.score(training_set, training_target)
knn_test_score = knn.score(test_set, test_target)
print('KNN training score = ', knn_training_score)
print("KNN test score = ", knn_test_score)

KNN training score =  0.9123573682932751
KNN test score =  0.8930999320190347


In [120]:
suportvm = svm.SVC().fit(training_set, training_target)
svm_training_score = suportvm.score(training_set, training_target)
svm_test_score = suportvm.score(test_set, test_target)
print('SVM training score = ', svm_training_score)
print("SVM test score = ", svm_test_score)

SVM training score =  0.9089584850691915
SVM test score =  0.8993396134796543


The highest accuracy is the Support Vector Machine

### Experiment 5

In [121]:
test_target.value_counts()

0    36548
1     4640
Name: y_yes, dtype: int64

It would be about a 88.73% accuracy if we predicted all no

### Experiment 6

In [128]:
dumb_pred = np.zeros_like(test_target)

metrics.confusion_matrix(test_target.to_numpy(), dumb_pred)

array([[36548,     0],
       [ 4640,     0]])

In [129]:
metrics.roc_auc_score(test_target.to_numpy(), dumb_pred)

0.5

### Experiment 7

In [132]:
gnb_pred = gnb.predict(test_set)
metrics.confusion_matrix(test_target, gnb_pred)


array([[21141, 15407],
       [ 1094,  3546]])

In [152]:
metrics.roc_auc_score(test_target,gnb_pred)

0.6713344614356935

In [134]:
knn_pred = knn.predict(test_set)
metrics.confusion_matrix(test_target, knn_pred)

array([[35606,   942],
       [ 3461,  1179]])

In [153]:
metrics.roc_auc_score(test_target, knn_pred)

0.6141602517048906

In [136]:
svm_pred = suportvm.predict(test_set)
metrics.confusion_matrix(test_target, svm_pred)

array([[36226,   322],
       [ 3824,   816]])

In [154]:
metrics.roc_auc_score(test_target, svm_pred)

0.583525868673412

The best classifier going by the auc score is the naive bayes which had the worst accuracy of the three

### Experiment 8

In [141]:
ros =  RandomOverSampler(random_state=(2021-4-22))
rs_training_set, rs_training_target = ros.fit_resample(training_set, training_target)
rs_test_set, rs_test_target = ros.fit_resample(test_set, test_target)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


### Eperiment 9

In [146]:
gnb2 = naive_bayes.GaussianNB().fit(rs_training_set, rs_training_target)
gnb_training_score2 = gnb2.score(rs_training_set, rs_training_target)
gnb_test_score2 = gnb2.score(rs_test_set, rs_test_target)
print('Naive Bayes2 training score = ', gnb_training_score2)
print("Naive Bayes2 test score = ", gnb_test_score2)

Naive Bayes2 training score =  0.6529443838604144
Naive Bayes2 test score =  0.6499945277443362


In [147]:
knn2 = neighbors.KNeighborsClassifier().fit(rs_training_set, rs_training_target)
knn_training_score2 = knn2.score(rs_training_set, rs_training_target)
knn_test_score2 = knn2.score(rs_test_set, rs_test_target)
print('KNN training score2 = ', knn_training_score2)
print("KNN test score = ", knn_test_score2)

KNN training score2 =  0.9169847328244275
KNN test score =  0.692377147860348


In [145]:
suportvm2 = svm.SVC().fit(rs_training_set, rs_training_target)
svm_training_score2 = suportvm2.score(rs_training_set, rs_training_target)
svm_test_score2 = suportvm2.score(rs_test_set, rs_test_target)
print('SVM training score = ', svm_training_score2)
print("SVM test score = ", svm_test_score2)

SVM training score =  0.7832606324972737
SVM test score =  0.7415727262777717


In [148]:
gnb_pred2 = gnb2.predict(rs_test_set)
metrics.confusion_matrix(rs_test_target, gnb_pred2)


array([[18482, 18066],
       [ 7518, 29030]])

In [150]:
metrics.roc_auc_score(rs_test_target,gnb_pred2)

0.6499945277443362

In [151]:
knn_pred2 = knn2.predict(rs_test_set)
metrics.confusion_matrix(rs_test_target, knn_pred2)

array([[28734,  7814],
       [14672, 21876]])

In [155]:
metrics.roc_auc_score(rs_test_target, knn_pred2)

0.6923771478603481

In [156]:
svm_pred2 = suportvm.predict(rs_test_set)
metrics.confusion_matrix(rs_test_target, svm_pred2)

array([[36226,   322],
       [30201,  6347]])

In [157]:
metrics.roc_auc_score(rs_test_target, svm_pred2)

0.5824258509357557

The KNN model has the highest AUC and it is about 0.08 better than the last one